### ISSUE TITLE
Setup Instructions Too Vague

### ISSUE THREAD

**Issue by Valkryst** [Emmsii/roguelikedev-does-the-complete-roguelike-tutorial#2] opened 2018-07-20 13:00 UTC
When cloning the repository, in order to set it up in IntelliJ, I found that most of the required settings weren't configured. The project is missing its POM file and neither the src/resources folder are marked as the sources/resources folder within IntelliJ.

To answer a [question](https://www.reddit.com/r/roguelikedev/comments/90emaq/stupid_question/), about how to clone and set up this repository, I actually had to create an entire [video](https://www.youtube.com/watch?v=KiLS955YxT8&feature=youtu.be) showing how to do it. I can't see anyone, without experience in using Maven and IntelliJ, being able to set up this project without a bit of a rework on your part.

Sorry if this came off as ranting, but it looks like some people are using this project for learning purposes, so it should be made as easy as possible for them to get it working

**Comment by Emmsii** [comment] 2018-07-20 13:49
Apologies for the poor setup instructions. I beleive I used [this](https://www.youtube.com/watch?v=uUzRMOCBorg) video to add the project to GitHub, I probably should have included the libraries folder in the commit or used Maven (something I am not familiar with).

I didn't realise how hard the project was to setup for users, I don't particularly want to leave it in this state. Would you be able to point me in the right direction of fixing the project so it's easier for users to import?

Thanks for creating a video, I can add it do the readme until the project is structured better.

**Comment by Valkryst** [comment] 2018-07-20 14:14
It's totally understandable, I still make mistakes when setting up my projects as well. =)

I'm currently updating a fork of the project and I'll send over a PR around the same time that I post this comment. Here's a list of everything I'm altering.

* Updated the *.gitignore* file using the one from [this project](https://github.com/Valkryst/StarterKit_Java_Maven).
* Added support for Maven to the project.
    * You'll want to tell users to change the name of the *<groupId>* value in the *pom.xml* file to something unique to them. For example, you're using *com.mac.rltut* and I commonly use *com.github.Valkryst*.
    * You can safely delete the entire *<build>* section if you want. I just add it to every project I work on. The comments explain why.
    * You should double-check the dependencies. I may be missing something, but they appear to be correct to me.
* Don't quote me on this, but I recall reading that the standard name for the resources folder is *res*. I suggest changing the folder name from *assets* to *res* if that is the case.
* I don't fully understand why you're using SLF4J, rather than the usual *System.out.println*. If there isn't any particular reason, I suggest removing SLF4J as a dependency to keep things simple for people using your code to learn.


The game also throws an exception when viewing the high scores from the main menu.

```
java.io.FileNotFoundException: s (The system cannot find the file specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at com.mac.rltut.engine.web.HttpRequest.get(HttpRequest.java:32)
	at com.mac.rltut.engine.web.HttpRequest.<init>(HttpRequest.java:22)
	at com.mac.rltut.game.screen.menu.HighscoresScreen.<init>(HighscoresScreen.java:42)
	at com.mac.rltut.game.screen.menu.StartScreen.input(StartScreen.java:41)
	at com.mac.rltut.engine.Engine.input(Engine.java:117)
	at com.mac.rltut.engine.input.Input.keyPressed(Input.java:22)
	at java.awt.Component.processKeyEvent(Component.java:6497)
	at java.awt.Component.processEvent(Component.java:6316)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Window.processEvent(Window.java:2025)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:835)
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1103)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:974)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:800)
	at java.awt.Component.dispatchEventImpl(Component.java:4760)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

Pressing ENTER on the options screen also does nothing as far as I can tell. Although pressing ESC appears to save the settings and bring you back to the main menu.

**Comment by Emmsii** [comment] 2018-07-20 15:05
Thanks for that, I should be able to take a look at your PR this weekend!

I think I used SLF4J as it was shorter to write `Log.info` than `System.out.println`, and it handled the formatting for me by adding the datetime as well as warn, error, info, etc.

The exception is caused by a missing file. It contained the IP of my highscores server (no longer online), I tried to obfuscate the IP address by 'hiding' it in a compressed file I serialized. If you look in [this method](https://github.com/Emmsii/roguelikedev-does-the-complete-roguelike-tutorial/blob/master/src/com/mac/rltut/engine/web/HttpRequest.java#L25) you can I see I load a file called 's', uncompress it, and read a URL from a string. It was a quick and dirty way to hide the IP from people looking around the .jar file. You should be able to find the 's' file if you open the final .jar file from the itch.io page.

Looking back, it was probably incredibly easy for someone to look at the source code, find out how to get the IP and forge their own highscores. I think I'll keep the highscores screen and the HttpRequest class, but remove the code for loading in the 's' file and write a note explaining what's going on.

As for the options screen doing nothing on ENTER, I think it's a typo either [here](https://github.com/Emmsii/roguelikedev-does-the-complete-roguelike-tutorial/blob/72b1984b51b73970e8f3081bd55c8b0d5b880431/src/com/mac/rltut/game/screen/menu/OptionsScreen.java#L34) or [here](https://github.com/Emmsii/roguelikedev-does-the-complete-roguelike-tutorial/blob/master/src/com/mac/rltut/game/screen/menu/OptionsScreen.java#L70). I either ment to write `KeyEvent.VK_ENTER` on line 34 or `"Press [ESCAPE] to save"`.

**Comment by Emmsii** [comment] 2018-07-22 10:02
I've merged your fork, thanks for your help!

**Closed as completed by Emmsii** 2018-07-22 10:02 UTC
Labels: help wanted
